# Generated by Django 4.2.24 on 2026-01-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_expense_date_cashreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
