# Generated by Django 4.2.24 on 2026-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_client_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Apartment'), ('office', 'Office')], max_length=20)),
                ('image', models.ImageField(upload_to='work_items/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='work_items/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='work_items/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
