# Generated by Django 4.2.24 on 2026-01-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_workitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='work_items/'),
        ),
    ]
