# Generated by Django 4.2.24 on 2026-01-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_workitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='discussion_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='discussion_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
