# Generated by Django 4.2.24 on 2026-01-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='expenses_discussion_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='expenses_discussion_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payments_discussion_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='payments_discussion_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
