# Generated by Django 4.2.24 on 2026-01-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_separate_discussion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='expenses_version_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='payments_version_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PaymentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('discussion_completed_at', models.DateTimeField()),
                ('payments_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_versions', to='api.client')),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('client', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('discussion_completed_at', models.DateTimeField()),
                ('expenses_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_versions', to='api.client')),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('client', 'version_number')},
            },
        ),
    ]
