# Generated by Django 4.2.24 on 2026-01-27 16:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_add_version_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='expenseversion',
            options={'ordering': ['-version_number'], 'verbose_name': 'Expense Version', 'verbose_name_plural': 'Expense Versions'},
        ),
        migrations.AlterModelOptions(
            name='paymentversion',
            options={'ordering': ['-version_number'], 'verbose_name': 'Payment Version', 'verbose_name_plural': 'Payment Versions'},
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this client was last updated'),
        ),
        migrations.AddField(
            model_name='expenseversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this version was last updated'),
        ),
        migrations.AddField(
            model_name='paymentversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this version was last updated'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Client address', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Client budget amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this client was created'),
        ),
        migrations.AlterField(
            model_name='client',
            name='discussion_completed',
            field=models.BooleanField(default=False, help_text='Legacy field: whether general discussion is completed'),
        ),
        migrations.AlterField(
            model_name='client',
            name='discussion_completed_at',
            field=models.DateTimeField(blank=True, help_text='Legacy field: when general discussion was completed', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='expenses_discussion_completed',
            field=models.BooleanField(default=False, help_text='Whether expenses discussion is completed'),
        ),
        migrations.AlterField(
            model_name='client',
            name='expenses_discussion_completed_at',
            field=models.DateTimeField(blank=True, help_text='When expenses discussion was completed', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='expenses_version_count',
            field=models.IntegerField(default=0, help_text='Number of expense versions created', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this client is active'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Whether this client is soft-deleted'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payments_discussion_completed',
            field=models.BooleanField(default=False, help_text='Whether payments discussion is completed'),
        ),
        migrations.AlterField(
            model_name='client',
            name='payments_discussion_completed_at',
            field=models.DateTimeField(blank=True, help_text='When payments discussion was completed', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='payments_version_count',
            field=models.IntegerField(default=0, help_text='Number of payment versions created', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Client phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='active', help_text='Current status of the client', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this client', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenseversion',
            name='client',
            field=models.ForeignKey(help_text='Client this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.client'),
        ),
        migrations.AlterField(
            model_name='expenseversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this version was created'),
        ),
        migrations.AlterField(
            model_name='expenseversion',
            name='discussion_completed_at',
            field=models.DateTimeField(help_text='When the discussion was completed'),
        ),
        migrations.AlterField(
            model_name='expenseversion',
            name='expenses_data',
            field=models.JSONField(help_text='Serialized expense data at the time of version creation'),
        ),
        migrations.AlterField(
            model_name='expenseversion',
            name='version_number',
            field=models.PositiveIntegerField(help_text='Version number (starts from 1)'),
        ),
        migrations.AlterField(
            model_name='paymentversion',
            name='client',
            field=models.ForeignKey(help_text='Client this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='api.client'),
        ),
        migrations.AlterField(
            model_name='paymentversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this version was created'),
        ),
        migrations.AlterField(
            model_name='paymentversion',
            name='discussion_completed_at',
            field=models.DateTimeField(help_text='When the discussion was completed'),
        ),
        migrations.AlterField(
            model_name='paymentversion',
            name='payments_data',
            field=models.JSONField(help_text='Serialized payment data at the time of version creation'),
        ),
        migrations.AlterField(
            model_name='paymentversion',
            name='version_number',
            field=models.PositiveIntegerField(help_text='Version number (starts from 1)'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user'], name='clients_user_id_ac8513_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_status_98ee60_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active', 'is_deleted'], name='clients_is_acti_aeae32_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['expenses_discussion_completed'], name='clients_expense_22a7d2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['payments_discussion_completed'], name='clients_payment_6585a9_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseversion',
            index=models.Index(fields=['client', 'version_number'], name='expense_ver_client__55571a_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseversion',
            index=models.Index(fields=['client', 'discussion_completed_at'], name='expense_ver_client__288d91_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseversion',
            index=models.Index(fields=['created_at'], name='expense_ver_created_b10fad_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentversion',
            index=models.Index(fields=['client', 'version_number'], name='payment_ver_client__b67e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentversion',
            index=models.Index(fields=['client', 'discussion_completed_at'], name='payment_ver_client__8f57ca_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentversion',
            index=models.Index(fields=['created_at'], name='payment_ver_created_c5a90d_idx'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='expenseversion',
            table='expense_versions',
        ),
        migrations.AlterModelTable(
            name='paymentversion',
            table='payment_versions',
        ),
    ]
